//Generated by common/gen_conf

package email

import "sync/atomic"

var _emailCsv atomic.Value

func EmailCsv() emailCsv { return _emailCsv.Load().(emailCsv) }
func NilEmailCsv() emailCsv { return nil }
func (v emailCsv) Init() { _emailCsv.Store(v) } //一块全新内存
