//Generated by common/gen_conf

package email

import "sync"

var (
	_emailCsv		 emailCsv
	_emailCsvMutex sync.Mutex
)

func EmailCsv() emailCsv {
	_emailCsvMutex.Lock()
	ret := _emailCsv //拷贝到栈上
	_emailCsvMutex.Unlock()
	return ret
}
func (v emailCsv) Init() {
	_emailCsvMutex.Lock()
	_emailCsv = v
	_emailCsvMutex.Unlock()
}
