//Generated by common/gen_conf

package email

import "sync/atomic"

var _invalidCsv atomic.Value

func InvalidCsv() invalidCsv { return _invalidCsv.Load().(invalidCsv) }
func NilInvalidCsv() invalidCsv { return nil }
func (v invalidCsv) Init() { _invalidCsv.Store(v) } //一块全新内存
