//Generated by common/gen_conf

package email

import "sync"

var (
	_invalidCsv		 invalidCsv
	_invalidCsvMutex sync.Mutex
)

func InvalidCsv() invalidCsv {
	_invalidCsvMutex.Lock()
	ret := _invalidCsv //拷贝到栈上
	_invalidCsvMutex.Unlock()
	return ret
}
func (v invalidCsv) Init() {
	_invalidCsvMutex.Lock()
	_invalidCsv = v
	_invalidCsvMutex.Unlock()
}
