// Generated by GoServer/src/generate
// Don't edit !
package err

const (
	Success uint16 = 1
	Unknow_error uint16 = 2
	Passwd_err uint16 = 3
	Account_none uint16 = 4
	Account_forbidden uint16 = 5
	Account_repeat uint16 = 6
	Account_format_err uint16 = 7
	Passwd_format_err uint16 = 8
	BindInfo_format_err uint16 = 9
	BindInfo_had_been_bound uint16 = 10
	Account_had_been_bound uint16 = 11
	None_free_game_server uint16 = 12
	None_center_server uint16 = 13
	None_login_server uint16 = 14
	None_gateway uint16 = 15
	None_game_server uint16 = 16
	None_battle_server uint16 = 17
	None_chat_server uint16 = 18
	None_file_server uint16 = 19
	None_friend_server uint16 = 20
	None_save_server uint16 = 21
	None_cross_server uint16 = 22
	None_sdk_server uint16 = 23
	Token_verify_err uint16 = 24
	Account_have_none_player uint16 = 25
	Sign_failed uint16 = 26
	Record_upload_failed uint16 = 27
	Record_cannot_find uint16 = 28
	Record_repeat uint16 = 29
	Record_download_limit uint16 = 30
	Account_without_bind_info uint16 = 31
	
)
