// Generated by GoServer/src/generat
// Don't edit !
package err

import (
	"common"
	"common/file"
)

var g_err_csv []common.StrPair

func ToString(errCode uint16) string {
	if g_err_csv == nil {
		file.G_Csv_Map["err_code"] = &g_err_csv
		file.LoadOneCsv("csv/err_code.csv")
	}
	return g_err_csv[errCode-1].V
}

const (
	Success uint16 = 1
	Passwd_err uint16 = 2
	Account_none uint16 = 3
	Account_forbidden uint16 = 4
	Account_repeat uint16 = 5
	Account_format_err uint16 = 6
	Passwd_format_err uint16 = 7
	BindInfo_format_err uint16 = 8
	BindInfo_had_been_bound uint16 = 9
	Account_had_been_bound uint16 = 10
	None_free_game_server uint16 = 11
	None_center_server uint16 = 12
	None_login_server uint16 = 13
	None_gateway uint16 = 14
	None_game_server uint16 = 15
	None_battle_server uint16 = 16
	None_chat_server uint16 = 17
	None_file_server uint16 = 18
	None_friend_server uint16 = 19
	None_save_server uint16 = 20
	None_cross_server uint16 = 21
	None_sdk_server uint16 = 22
	Token_verify_err uint16 = 23
	Account_have_none_player uint16 = 24
	
)
