//Generated by common/gen_conf

package main

import "sync"

var (
	_logins		 logins
	_loginsMutex sync.Mutex
)

func Logins() logins {
	_loginsMutex.Lock()
	ret := _logins //拷贝到栈上
	_loginsMutex.Unlock()
	return ret
}
func (v logins) Init() {
	_loginsMutex.Lock()
	_logins = v
	_loginsMutex.Unlock()
}
