
// Generated by GoServer/src/generat
// Don't edit !
package rpc
import (
	"common/net/register"
	"generate_out/rpc/enum"
	
	
	"svr_file/logic"
)
func init() {
	register.RegTcpRpc(map[uint16]register.TcpRpc{
		
	})
	register.RegHttpRpc(map[uint16]register.HttpRpc{
		
		enum.Rpc_file_update_list: logic.Rpc_file_update_list,
	})
	register.RegHttpPlayerRpc(map[uint16]register.HttpPlayerRpc{
		
	})
	register.RegHttpHandler(map[string]register.HttpHandle{
		
		"file_upload": logic.Http_file_upload,
	})
}
