// Generated by GoServer/src/generate
// Don't edit !
package rpc
import (
	"netConfig/register"
	"generate_out/rpc/enum"
	"shared_svr/zookeeper/logic"
	
)
func init() {
	
		register.RegTcpRpc(map[uint16]register.TcpRpc{
			enum.Rpc_net_error: logic.Rpc_net_error,
			enum.Rpc_zoo_register: logic.Rpc_zoo_register,
			
		})
	
	
	
	
}
