/***********************************************************************
* @ 生成错误码枚举
* @ brief
	1、配表 csv/err_code.csv 首列为枚举名

	2、解析 generate_out/err/generate_err_code.go，得到旧的错误码枚举

	3、新错误码只允许追加在表后，保障兼容性

	4、手动删除 generate_err_code.go 才会整个重新生成

* @ author zhoumf
* @ date 2018-9-3
***********************************************************************/
package main

import (
	"common/file"
	"common/std"
	"regexp"
	"strconv"
	"strings"
)

type ErrEnum struct {
	Name string
	Desc string
}

func generateErrCode() {
	var errCsv []ErrEnum
	file.LoadCsv("csv/err_code.csv", &errCsv)

	enums, enumCnt := getOldErr() //旧枚举，追加新增入后重新生成
	haveNewEnum := false
	for _, v := range errCsv {
		if !IsEnumIn(enums, v.Name) {
			enums = append(enums, std.KeyPair{v.Name, enumCnt})
			haveNewEnum = true
			enumCnt++
		}
	}
	if !haveNewEnum { //没有新的，就不改动文件了，编译更友好
		println("no new errCode, don't change err_code.h")
		return
	}

	println(K_ErrOutDir, K_ErrFileName+".go")
	file.CreateTemplate(enums, K_ErrOutDir, K_ErrFileName+".go", codeErrTemplate_Go)

	if K_ErrOutDir_C != "" {
		println(K_ErrOutDir_C, K_ErrFileName+".h")
		file.CreateTemplate(enums, K_ErrOutDir_C, K_ErrFileName+".h", codeErrTemplate_C)
	}
	if K_ErrOutDir_CS != "" {
		println(K_ErrOutDir_CS, K_ErrFileName+".cs")
		file.CreateTemplate(enums, K_ErrOutDir_CS, K_ErrFileName+".cs", codeErrTemplate_CS)
	}
}
func getOldErr() (enums []std.KeyPair, enumCnt int) {
	reg := regexp.MustCompile(`\w+`)
	file.ReadLine(K_ErrOutDir+K_ErrFileName+".go", func(line string) {
		if ok, _ := regexp.MatchString(`\w+ uint16 =`, line); ok {
			if result := reg.FindAllString(line, -1); result != nil {
				name := result[0]
				list := strings.Split(line, " ")
				rid, _ := strconv.Atoi(list[len(list)-1])
				enums, enumCnt = append(enums, std.KeyPair{name, rid}), rid+1
			}
		}
	})
	if enumCnt < 100 { //之前的预留给系统层用
		enumCnt = 100
	}
	return
}

// -------------------------------------
// -- 填充模板
const (
	codeErrTemplate_Go = `// Generated by GoServer/src/generate
// Don't edit !
package err

const ( //the top 100 are reserved for system
	{{range $_, $v := .}}{{$v.Name}} uint16 = {{$v.ID}}
	{{end}}
)
`
	codeErrTemplate_C = `// Generated by GoServer/src/generate
// Don't edit !
#pragma once

namespace Err
{
	enum ErrEnum : uint16 {
		{{range $_, $v := .}}{{$v.Name}} = {{$v.ID}},
		{{end}}
	};
}
`
	codeErrTemplate_CS = `// Generated by GoServer/src/generate
// Don't edit !
public enum Err : System.UInt16 {
	{{range $_, $v := .}}{{$v.Name}} = {{$v.ID}},
	{{end}}
}
`
)
