// Generated by GoServer/src/generate
// Don't edit !
package enum
const ( //the top 100 are reserved for system
	Rpc_regist uint16 = 1
	Rpc_unregist uint16 = 2
	Rpc_svr_accept uint16 = 3
	Rpc_net_error uint16 = 4
	Rpc_svr_node_join uint16 = 5
	Rpc_http_node_quit uint16 = 6
	Rpc_recv_player_msg uint16 = 7
	Rpc_gm_cmd uint16 = 8
	Rpc_log uint16 = 9
	Rpc_meta_list uint16 = 10
	Rpc_update_csv uint16 = 11
	Rpc_reload_csv uint16 = 12
	Rpc_zoo_register uint16 = 100
	Rpc_center_account_login uint16 = 101
	Rpc_center_account_reg uint16 = 102
	Rpc_center_account_check uint16 = 103
	Rpc_center_change_password uint16 = 104
	Rpc_center_bind_info uint16 = 105
	Rpc_center_get_account_by_bind_info uint16 = 106
	Rpc_center_set_game_info uint16 = 107
	Rpc_login_account_login uint16 = 108
	Rpc_gateway_relay_game_login uint16 = 109
	Rpc_gateway_relay_game_create_player uint16 = 110
	Rpc_login_get_meta_list uint16 = 111
	Rpc_login_relay_to_center uint16 = 112
	Rpc_gateway_relay_player_msg uint16 = 113
	Rpc_center_create_visitor uint16 = 114
	Rpc_center_ask_reset_password uint16 = 115
	Rpc_file_update_list uint16 = 116
	Rpc_friend_get_friend_list uint16 = 117
	Rpc_friend_add uint16 = 118
	Rpc_friend_del uint16 = 119
	Rpc_gateway_login uint16 = 120
	Rpc_gateway_login_token uint16 = 121
	Rpc_gateway_relay_module uint16 = 122
	Rpc_gateway_relay_modules uint16 = 123
	Rpc_save_get_meta_info uint16 = 125
	Rpc_save_upload_binary2 uint16 = 126
	Rpc_save_download_data uint16 = 127
	Rpc_save_upload_binary uint16 = 128
	Rpc_save_download_binary uint16 = 129
	Rpc_cross_relay_battle_data uint16 = 130
	Rpc_cross_relay_to_game uint16 = 131
	Rpc_game_login uint16 = 132
	Rpc_game_create_player uint16 = 133
	Rpc_game_login_token uint16 = 134
	Rpc_game_write_db_battle_info uint16 = 135
	Rpc_game_on_battle_end uint16 = 136
	Rpc_game_heart_beat uint16 = 137
	Rpc_game_logout uint16 = 138
	Rpc_game_get_mail uint16 = 139
	Rpc_game_read_mail uint16 = 140
	Rpc_game_del_mail uint16 = 141
	Rpc_game_take_all_mail_item uint16 = 142
	Rpc_game_season_info uint16 = 143
	Rpc_game_get_show_info uint16 = 144
	Rpc_game_battle_begin uint16 = 145
	Rpc_game_exit_team uint16 = 146
	Rpc_game_join_team uint16 = 147
	Rpc_game_agree_invite uint16 = 148
	Rpc_game_become_captain uint16 = 149
	Rpc_game_get_team_info uint16 = 150
	Rpc_game_team_chat uint16 = 151
	Rpc_order_success uint16 = 152
	Rpc_order_info uint16 = 153
	Rpc_battle_login uint16 = 154
	Rpc_battle_logout uint16 = 155
	Rpc_battle_reconnect uint16 = 156
	Rpc_battle_join_room uint16 = 157
	Rpc_battle_exit_room uint16 = 158
	Rpc_battle_direct_join_room uint16 = 159
	Rpc_battle_handle_move_input uint16 = 160
	Rpc_battle_handle_fire_input uint16 = 161
	Rpc_battle_handle_trigger_enter uint16 = 162
	Rpc_battle_handle_trigger_exit uint16 = 163
	Rpc_battle_forward_anim_state uint16 = 164
	Rpc_battle_pick_weapon uint16 = 165
	Rpc_battle_drop_weapon uint16 = 166
	Rpc_battle_change_weapon uint16 = 167
	Rpc_battle_get_scoreboard uint16 = 168
	Rpc_battle_skill_use uint16 = 169
	Rpc_battle_skill_break uint16 = 170
	Rpc_battle_passive_skill_select uint16 = 171
	Rpc_battle_hit_by_sword uint16 = 172
	Rpc_battle_hit_by_laser uint16 = 173
	Rpc_battle_transfer uint16 = 174
	Rpc_battle_sync_boss_skill_event uint16 = 175
	Rpc_battle_check_hero_skill_cd uint16 = 176
	Rpc_battle_handle_player_data uint16 = 177
	Rpc_client_sync_player_join_info uint16 = 178
	Rpc_client_spawn_player uint16 = 179
	Rpc_client_notify_player_exit_room uint16 = 180
	Rpc_client_stop_wait_and_select_hero uint16 = 181
	Rpc_client_stop_wait_and_select_boss uint16 = 182
	Rpc_client_sync_map uint16 = 183
	Rpc_client_sync_predict_objs_position uint16 = 184
	Rpc_client_sync_objs_position_facing uint16 = 185
	Rpc_client_sync_objs_position_rotation uint16 = 186
	Rpc_client_sync_generic_attrs uint16 = 187
	Rpc_client_handle_spawn_attrs uint16 = 188
	Rpc_client_spawn_object uint16 = 189
	Rpc_client_sync_anim_state uint16 = 190
	Rpc_client_sync_pickup_weapon uint16 = 191
	Rpc_client_sync_drop_weapon uint16 = 192
	Rpc_client_sync_change_weapon uint16 = 193
	Rpc_client_sync_trigger_enter uint16 = 194
	Rpc_client_sync_trigger_exit uint16 = 195
	Rpc_client_sync_buff_add uint16 = 196
	Rpc_client_sync_buff_del uint16 = 197
	Rpc_client_passive_skill_select uint16 = 198
	Rpc_client_destroy_object uint16 = 199
	Rpc_client_destroy_room uint16 = 200
	Rpc_client_use_skill_double_gun uint16 = 201
	Rpc_client_skill_double_gun_break uint16 = 202
	Rpc_client_use_skill_turret uint16 = 203
	Rpc_client_use_skill_roll uint16 = 204
	Rpc_client_use_skill_shadow_blade uint16 = 205
	Rpc_client_boss_skill_event uint16 = 206
	Rpc_client_weapon_fire uint16 = 207
	Rpc_client_show_wait_ui uint16 = 208
	Rpc_client_login_battle uint16 = 209
	Rpc_client_bullet_netid uint16 = 210
	Rpc_client_on_other_join_team uint16 = 211
	Rpc_client_on_self_join_team uint16 = 212
	Rpc_client_on_exit_team uint16 = 213
	Rpc_client_be_invited uint16 = 214
	Rpc_client_team_chat uint16 = 215
	Rpc_client_friend_login uint16 = 216
	Rpc_client_friend_logout uint16 = 217
	Rpc_client_friend_add uint16 = 218
	Rpc_client_friend_del uint16 = 219
	Rpc_client_friend_apply uint16 = 220
	Rpc_center_account_forbid uint16 = 221
	Rpc_center_player_login_addr uint16 = 222
	Rpc_login_bulletin uint16 = 223
	Rpc_login_get_gift uint16 = 224
	Rpc_login_get_game_list uint16 = 225
	Rpc_login_move_player_db uint16 = 226
	Rpc_game_move_player_db uint16 = 227
	Rpc_game_move_player_db2 uint16 = 228
	Rpc_save_check_mac uint16 = 229
	Rpc_save_unbind_mac_by_email uint16 = 230
	Rpc_game_show_player_award uint16 = 231
	Rpc_game_get_player_award_ok uint16 = 232
	Rpc_game_gm_add_award uint16 = 233
	Rpc_game_gm_set_award uint16 = 234
	Rpc_game_gm_del_award uint16 = 235
	Rpc_battle_pick_armor uint16 = 236
	Rpc_client_sync_pickup_armor uint16 = 237
	Rpc_client_sync_drop_armor uint16 = 238
	Rpc_center_get_bind_info uint16 = 239
	Rpc_save_unbind_mac uint16 = 240
	Rpc_battle_add_weapon_unit uint16 = 241
	Rpc_battle_del_weapon_unit uint16 = 242
	Rpc_client_sync_add_weapon_unit uint16 = 243
	Rpc_client_sync_del_weapon_unit uint16 = 244
	Rpc_login_relay_email uint16 = 245
	RpcEnumCnt uint16 = 246
	
)
func GetRpcModule(rpcEnum uint16) string {
switch rpcEnum {
case
	Rpc_client_sync_player_join_info,
	Rpc_client_spawn_player,
	Rpc_client_notify_player_exit_room,
	Rpc_client_stop_wait_and_select_hero,
	Rpc_client_stop_wait_and_select_boss,
	Rpc_client_sync_map,
	Rpc_client_sync_predict_objs_position,
	Rpc_client_sync_objs_position_facing,
	Rpc_client_sync_objs_position_rotation,
	Rpc_client_sync_generic_attrs,
	Rpc_client_handle_spawn_attrs,
	Rpc_client_spawn_object,
	Rpc_client_sync_anim_state,
	Rpc_client_sync_pickup_weapon,
	Rpc_client_sync_drop_weapon,
	Rpc_client_sync_change_weapon,
	Rpc_client_sync_pickup_armor,
	Rpc_client_sync_drop_armor,
	Rpc_client_sync_add_weapon_unit,
	Rpc_client_sync_del_weapon_unit,
	Rpc_client_sync_trigger_enter,
	Rpc_client_sync_trigger_exit,
	Rpc_client_sync_buff_add,
	Rpc_client_sync_buff_del,
	Rpc_client_passive_skill_select,
	Rpc_client_destroy_object,
	Rpc_client_destroy_room,
	Rpc_client_use_skill_double_gun,
	Rpc_client_skill_double_gun_break,
	Rpc_client_use_skill_turret,
	Rpc_client_use_skill_roll,
	Rpc_client_use_skill_shadow_blade,
	Rpc_client_boss_skill_event,
	Rpc_client_weapon_fire,
	Rpc_client_show_wait_ui,
	Rpc_client_login_battle,
	Rpc_client_bullet_netid,
	Rpc_client_on_other_join_team,
	Rpc_client_on_self_join_team,
	Rpc_client_on_exit_team,
	Rpc_client_be_invited,
	Rpc_client_team_chat,
	Rpc_client_friend_login,
	Rpc_client_friend_logout,
	Rpc_client_friend_add,
	Rpc_client_friend_del,
	Rpc_client_friend_apply: return "client"
case
	Rpc_center_account_login,
	Rpc_center_account_reg,
	Rpc_center_account_check,
	Rpc_center_change_password,
	Rpc_center_create_visitor,
	Rpc_center_set_game_info,
	Rpc_center_player_login_addr,
	Rpc_center_bind_info,
	Rpc_center_get_account_by_bind_info,
	Rpc_center_get_bind_info: return "center"
case
	Rpc_file_update_list: return "file"
case
	Rpc_friend_get_friend_list,
	Rpc_friend_add,
	Rpc_friend_del: return "friend"
case
	Rpc_gateway_login,
	Rpc_gateway_relay_game_login,
	Rpc_gateway_relay_game_create_player,
	Rpc_gateway_login_token,
	Rpc_gateway_relay_module,
	Rpc_gateway_relay_modules,
	Rpc_gateway_relay_player_msg: return "gateway"
case
	Rpc_login_bulletin,
	Rpc_login_get_gift,
	Rpc_login_account_login,
	Rpc_login_relay_to_center,
	Rpc_login_get_game_list,
	Rpc_login_move_player_db,
	Rpc_login_relay_email: return "login"
case
	Rpc_save_get_meta_info,
	Rpc_save_check_mac,
	Rpc_save_upload_binary,
	Rpc_save_upload_binary2,
	Rpc_save_download_binary,
	Rpc_save_unbind_mac_by_email,
	Rpc_save_unbind_mac: return "save"
case
	Rpc_cross_relay_battle_data,
	Rpc_cross_relay_to_game: return "cross"
case
	Rpc_game_show_player_award,
	Rpc_game_get_player_award_ok,
	Rpc_game_gm_add_award,
	Rpc_game_gm_set_award,
	Rpc_game_gm_del_award,
	Rpc_game_login,
	Rpc_game_create_player,
	Rpc_game_login_token,
	Rpc_game_move_player_db2,
	Rpc_game_write_db_battle_info,
	Rpc_game_on_battle_end,
	Rpc_game_heart_beat,
	Rpc_game_logout,
	Rpc_game_get_mail,
	Rpc_game_read_mail,
	Rpc_game_del_mail,
	Rpc_game_take_all_mail_item,
	Rpc_game_move_player_db,
	Rpc_game_season_info,
	Rpc_game_get_show_info,
	Rpc_game_battle_begin,
	Rpc_game_exit_team,
	Rpc_game_join_team,
	Rpc_game_agree_invite,
	Rpc_game_become_captain,
	Rpc_game_get_team_info,
	Rpc_game_team_chat: return "game"}
return ""}