
// Generated by GoServer/src/generat
// Don't edit !
package enum
const ( //the top 100 rpc are reserved for net system
	Rpc_regist uint16 = 1
	Rpc_unregist uint16 = 2
	Rpc_svr_accept uint16 = 3
	Rpc_net_error uint16 = 4
	Rpc_svr_node_join uint16 = 5
	Rpc_http_node_quit uint16 = 6
	Rpc_recv_player_msg uint16 = 7
	Rpc_zoo_register uint16 = 100
)
