// Generated by GoServer/src/generate
// Don't edit !
package enum
import "conf"
const ( //the top 100 are reserved for system
	Rpc_regist uint16 = 1
	Rpc_unregist uint16 = 2
	Rpc_svr_accept uint16 = 3
	Rpc_net_error uint16 = 4
	Rpc_node_join uint16 = 5
	Rpc_node_quit uint16 = 6
	Rpc_recv_player_msg uint16 = 7
	Rpc_gm_cmd uint16 = 8
	Rpc_log uint16 = 9
	Rpc_meta_list uint16 = 10
	Rpc_update_file uint16 = 11
	Rpc_reload_csv uint16 = 12
	Rpc_get_meta uint16 = 13
	Rpc_timestamp uint16 = 14
	Rpc_center_account_login2 uint16 = 15
	Rpc_center_account_reg2 uint16 = 16
	Rpc_center_platform_reg uint16 = 17
	Rpc_center_reg_if2 uint16 = 18
	Rpc_center_change_password2 uint16 = 19
	Rpc_center_set_game_route2 uint16 = 20
	Rpc_center_set_game_json2 uint16 = 21
	Rpc_center_game_info2 uint16 = 22
	Rpc_center_player_login_addr2 uint16 = 23
	Rpc_center_bind_info2 uint16 = 24
	Rpc_center_isvalid_bind_info2 uint16 = 25
	Rpc_nric_set2 uint16 = 26
	Rpc_nric_birthday2 uint16 = 27
	Rpc_nric_copy_to2 uint16 = 28
	Rpc_nric_online_time_get2 uint16 = 29
	Rpc_nric_online_time_set2 uint16 = 30
	Rpc_set_identity uint16 = 31
	Rpc_check_identity uint16 = 32
	Rpc_zoo_register uint16 = 100
	Rpc_center_account_login uint16 = 101
	Rpc_center_account_reg uint16 = 102
	Rpc_center_account_check uint16 = 103
	Rpc_center_change_password uint16 = 104
	Rpc_center_bind_info uint16 = 105
	Rpc_center_get_account_by_bind_info uint16 = 106
	Rpc_center_set_game_info uint16 = 107
	Rpc_login_account_login uint16 = 108
	Rpc_gateway_relay_game_login uint16 = 109
	Rpc_gateway_relay_game_create_player uint16 = 110
	Rpc_login_get_meta_list uint16 = 111
	Rpc_login_relay_to_center uint16 = 112
	Rpc_gateway_relay uint16 = 113
	Rpc_center_create_visitor uint16 = 114
	Rpc_center_ask_reset_password uint16 = 115
	Rpc_file_update_list uint16 = 116
	Rpc_friend_list uint16 = 117
	Rpc_friend_add uint16 = 118
	Rpc_friend_del uint16 = 119
	Rpc_gateway_login uint16 = 120
	Rpc_gateway_login_token uint16 = 121
	Rpc_gateway_to_svr uint16 = 122
	Rpc_gateway_relay_modules uint16 = 123
	Rpc_save_get_meta_info uint16 = 125
	Rpc_save_upload_binary2 uint16 = 126
	Rpc_save_download_data uint16 = 127
	Rpc_save_upload_binary uint16 = 128
	Rpc_save_download_binary uint16 = 129
	Rpc_cross_relay_battle_data uint16 = 130
	Rpc_cross_relay_to_game uint16 = 131
	Rpc_game_login uint16 = 132
	Rpc_game_player_set_name uint16 = 133
	Rpc_game_login_token uint16 = 134
	Rpc_game_write_db_battle_info uint16 = 135
	Rpc_game_on_battle_end uint16 = 136
	Rpc_game_heart_beat uint16 = 137
	Rpc_game_logout uint16 = 138
	Rpc_game_get_mail uint16 = 139
	Rpc_game_read_mail uint16 = 140
	Rpc_game_del_mail uint16 = 141
	Rpc_game_take_all_mail_item uint16 = 142
	Rpc_game_season_info uint16 = 143
	Rpc_game_get_show_info uint16 = 144
	Rpc_game_battle_begin uint16 = 145
	Rpc_game_exit_team uint16 = 146
	Rpc_game_join_team uint16 = 147
	Rpc_game_agree_invite uint16 = 148
	Rpc_game_become_captain uint16 = 149
	Rpc_game_get_team_info uint16 = 150
	Rpc_game_team_chat uint16 = 151
	Rpc_order_success uint16 = 152
	Rpc_order_info uint16 = 153
	Rpc_battle_login uint16 = 154
	Rpc_battle_logout uint16 = 155
	Rpc_battle_reconnect uint16 = 156
	Rpc_battle_join_room uint16 = 157
	Rpc_battle_exit_room uint16 = 158
	Rpc_battle_direct_join_room uint16 = 159
	Rpc_battle_handle_move_input uint16 = 160
	Rpc_battle_handle_fire_input uint16 = 161
	Rpc_battle_handle_trigger_enter uint16 = 162
	Rpc_battle_handle_trigger_exit uint16 = 163
	Rpc_battle_forward_anim_state uint16 = 164
	Rpc_battle_pick_weapon uint16 = 165
	Rpc_battle_drop_weapon uint16 = 166
	Rpc_battle_change_weapon uint16 = 167
	Rpc_battle_get_scoreboard uint16 = 168
	Rpc_battle_skill_use uint16 = 169
	Rpc_battle_skill_break uint16 = 170
	Rpc_battle_passive_skill_select uint16 = 171
	Rpc_battle_hit_by_sword uint16 = 172
	Rpc_battle_hit_by_laser uint16 = 173
	Rpc_battle_transfer uint16 = 174
	Rpc_battle_sync_boss_skill_event uint16 = 175
	Rpc_battle_check_hero_skill_cd uint16 = 176
	Rpc_battle_handle_player_data uint16 = 177
	Rpc_client_sync_player_join_info uint16 = 178
	Rpc_client_spawn_player uint16 = 179
	Rpc_client_notify_player_exit_room uint16 = 180
	Rpc_client_stop_wait_and_select_hero uint16 = 181
	Rpc_client_stop_wait_and_select_boss uint16 = 182
	Rpc_client_sync_map uint16 = 183
	Rpc_client_sync_predict_objs_position uint16 = 184
	Rpc_client_sync_objs_position_facing uint16 = 185
	Rpc_client_sync_objs_position_rotation uint16 = 186
	Rpc_client_sync_generic_attrs uint16 = 187
	Rpc_client_handle_spawn_attrs uint16 = 188
	Rpc_client_spawn_object uint16 = 189
	Rpc_client_sync_anim_state uint16 = 190
	Rpc_client_sync_pickup_weapon uint16 = 191
	Rpc_client_sync_drop_weapon uint16 = 192
	Rpc_client_sync_change_weapon uint16 = 193
	Rpc_client_sync_trigger_enter uint16 = 194
	Rpc_client_sync_trigger_exit uint16 = 195
	Rpc_client_sync_buff_add uint16 = 196
	Rpc_client_sync_buff_del uint16 = 197
	Rpc_client_passive_skill_select uint16 = 198
	Rpc_client_destroy_object uint16 = 199
	Rpc_client_destroy_room uint16 = 200
	Rpc_client_use_skill_double_gun uint16 = 201
	Rpc_client_skill_double_gun_break uint16 = 202
	Rpc_client_use_skill_turret uint16 = 203
	Rpc_client_use_skill_roll uint16 = 204
	Rpc_client_use_skill_shadow_blade uint16 = 205
	Rpc_client_boss_skill_event uint16 = 206
	Rpc_client_weapon_fire uint16 = 207
	Rpc_client_show_wait_ui uint16 = 208
	Rpc_client_login_battle uint16 = 209
	Rpc_client_bullet_netid uint16 = 210
	Rpc_client_on_other_join_team uint16 = 211
	Rpc_client_on_self_join_team uint16 = 212
	Rpc_client_on_exit_team uint16 = 213
	Rpc_client_be_invited uint16 = 214
	Rpc_client_team_chat uint16 = 215
	Rpc_client_friend_login uint16 = 216
	Rpc_client_friend_logout uint16 = 217
	Rpc_client_friend_add uint16 = 218
	Rpc_client_friend_del uint16 = 219
	Rpc_client_friend_apply uint16 = 220
	Rpc_center_account_forbid uint16 = 221
	Rpc_center_player_login_addr uint16 = 222
	Rpc_login_bulletin uint16 = 223
	Rpc_login_get_gift uint16 = 224
	Rpc_login_get_game_list uint16 = 225
	Rpc_login_move_player_db uint16 = 226
	Rpc_game_move_player_db uint16 = 227
	Rpc_game_move_player_db2 uint16 = 228
	Rpc_save_check_mac uint16 = 229
	Rpc_save_gm_up uint16 = 230
	Rpc_game_show_player_award uint16 = 231
	Rpc_game_get_player_award_ok uint16 = 232
	Rpc_game_gm_add_award uint16 = 233
	Rpc_game_gm_set_award uint16 = 234
	Rpc_game_gm_del_award uint16 = 235
	Rpc_battle_pick_armor uint16 = 236
	Rpc_client_sync_pickup_armor uint16 = 237
	Rpc_client_sync_drop_armor uint16 = 238
	Rpc_center_get_bind_info uint16 = 239
	Rpc_center_account_reg_force uint16 = 240
	Rpc_center_friend_add uint16 = 241
	Rpc_center_friend_del uint16 = 242
	Rpc_center_friend_list uint16 = 243
	Rpc_center_game_info uint16 = 244
	Rpc_center_get_game_json uint16 = 245
	Rpc_center_isvalid_bind_info uint16 = 246
	Rpc_center_player_login_addr_2 uint16 = 247
	Rpc_center_account_222 uint16 = 248
	Rpc_center_reg_if uint16 = 249
	Rpc_center_set_game_json uint16 = 250
	Rpc_center_set_game_route uint16 = 251
	Rpc_file_delete uint16 = 252
	Rpc_game_friend_add uint16 = 253
	Rpc_game_friend_del uint16 = 254
	Rpc_game_friend_list uint16 = 255
	Rpc_game_get_team_show_info uint16 = 256
	Rpc_game_permit_player uint16 = 257
	Rpc_game_ui_guns uint16 = 258
	Rpc_game_ui_heros uint16 = 259
	Rpc_game_whitelist_add uint16 = 260
	Rpc_game_whitelist_del uint16 = 261
	Rpc_gm_forbid_add uint16 = 262
	Rpc_gm_forbid_check uint16 = 263
	Rpc_gm_forbid_del uint16 = 264
	Rpc_gm_is_white uint16 = 265
	Rpc_login_del_account_cache uint16 = 266
	Rpc_login_gift_get uint16 = 267
	Rpc_login_send_email uint16 = 268
	Rpc_login_to_center_by_id uint16 = 269
	Rpc_login_to_center_by_str uint16 = 270
	Rpc_nric_birthday uint16 = 271
	Rpc_nric_copy_to uint16 = 272
	Rpc_nric_online_time_get uint16 = 273
	Rpc_nric_online_time_set uint16 = 274
	Rpc_nric_set uint16 = 275
	Rpc_relay_exit_room uint16 = 276
	Rpc_relay_join_room uint16 = 277
	Rpc_relay_login uint16 = 278
	Rpc_relay_new_room uint16 = 279
	Rpc_relay_report_input uint16 = 280
	Rpc_relay_to_other uint16 = 281
	Rpc_relay_to_others uint16 = 282
	Rpc_center_player_addr2 uint16 = 283
	Rpc_gm_white_black uint16 = 284
	Rpc_battle_change_hero uint16 = 285
	Rpc_battle_debug_moba_begin uint16 = 286
	Rpc_battle_drop_from_inventory uint16 = 287
	Rpc_battle_gm_command uint16 = 288
	Rpc_battle_gun_aim_break uint16 = 289
	Rpc_battle_hit_by_shield uint16 = 290
	Rpc_battle_hit_by_skill uint16 = 291
	Rpc_battle_inventory_drop_all uint16 = 292
	Rpc_battle_inventory_swap_items uint16 = 293
	Rpc_battle_pick_item uint16 = 294
	Rpc_battle_pull_teammate uint16 = 295
	Rpc_battle_restore_client_room uint16 = 296
	Rpc_battle_revive_all_teammate uint16 = 297
	Rpc_battle_use_potion uint16 = 298
	Rpc_client_battle_end uint16 = 299
	Rpc_client_call_obj_method uint16 = 300
	Rpc_client_moba_on_player_join uint16 = 301
	Rpc_client_safe_area_next_pos_radius uint16 = 302
	Rpc_client_safe_area_next_time uint16 = 303
	Rpc_client_sync_add_weapon_unit uint16 = 304
	Rpc_client_sync_del_weapon_unit uint16 = 305
	Rpc_client_sync_drop_from_inventory uint16 = 306
	Rpc_client_sync_inventory_drop_all uint16 = 307
	Rpc_client_sync_inventory_stack_items uint16 = 308
	Rpc_client_sync_inventory_swap_items uint16 = 309
	Rpc_client_sync_pick_to_inventory uint16 = 310
	Rpc_client_sync_pickup_potion uint16 = 311
	Rpc_client_sync_pickup_weapon_unit uint16 = 312
	Rpc_client_use_skill uint16 = 313
	Rpc_Samurai_sword_complete uint16 = 314
	Rpc_client_sync_sword_complete uint16 = 315
	Rpc_game_daily_sign_in uint16 = 316
	Rpc_game_look_over_daily_sign_in uint16 = 317
	Rpc_game_player_info uint16 = 318
	Rpc_gm_gift_get uint16 = 319
	Rpc_svr_node_join uint16 = 320
	RpcEnumCnt uint16 = 321
	
)
func GetRpcModule(rpcEnum uint16) string {
switch rpcEnum {
case
	Rpc_gateway_relay: return "gateway"
case
	Rpc_gm_forbid_add,
	Rpc_gm_forbid_check,
	Rpc_gm_forbid_del,
	Rpc_gm_gift_get,
	Rpc_gm_white_black: return "gm"
case
	Rpc_nric_birthday,
	Rpc_nric_copy_to,
	Rpc_nric_online_time_get,
	Rpc_nric_online_time_set,
	Rpc_nric_set: return "sdk"
case
	Rpc_relay_exit_room,
	Rpc_relay_join_room,
	Rpc_relay_new_room,
	Rpc_relay_report_input,
	Rpc_relay_to_other,
	Rpc_relay_to_others: return "relay"
case
	Rpc_center_account_login,
	Rpc_center_account_reg,
	Rpc_center_account_reg2,
	Rpc_center_account_reg_force,
	Rpc_center_bind_info,
	Rpc_center_bind_info2,
	Rpc_center_change_password2,
	Rpc_center_game_info2,
	Rpc_center_get_game_json,
	Rpc_center_isvalid_bind_info,
	Rpc_center_isvalid_bind_info2,
	Rpc_center_platform_reg,
	Rpc_center_player_addr2,
	Rpc_center_player_login_addr,
	Rpc_center_player_login_addr_2,
	Rpc_center_reg_if,
	Rpc_center_reg_if2,
	Rpc_center_set_game_json,
	Rpc_center_set_game_json2,
	Rpc_center_set_game_route,
	Rpc_center_set_game_route2: return "center"
case
	Rpc_client_battle_end,
	Rpc_client_be_invited,
	Rpc_client_boss_skill_event,
	Rpc_client_call_obj_method,
	Rpc_client_destroy_object,
	Rpc_client_friend_add,
	Rpc_client_friend_apply,
	Rpc_client_friend_del,
	Rpc_client_friend_login,
	Rpc_client_friend_logout,
	Rpc_client_handle_spawn_attrs,
	Rpc_client_login_battle,
	Rpc_client_moba_on_player_join,
	Rpc_client_notify_player_exit_room,
	Rpc_client_on_exit_team,
	Rpc_client_on_other_join_team,
	Rpc_client_on_self_join_team,
	Rpc_client_passive_skill_select,
	Rpc_client_safe_area_next_pos_radius,
	Rpc_client_safe_area_next_time,
	Rpc_client_show_wait_ui,
	Rpc_client_skill_double_gun_break,
	Rpc_client_spawn_object,
	Rpc_client_spawn_player,
	Rpc_client_stop_wait_and_select_boss,
	Rpc_client_stop_wait_and_select_hero,
	Rpc_client_sync_add_weapon_unit,
	Rpc_client_sync_anim_state,
	Rpc_client_sync_buff_add,
	Rpc_client_sync_buff_del,
	Rpc_client_sync_change_weapon,
	Rpc_client_sync_del_weapon_unit,
	Rpc_client_sync_drop_from_inventory,
	Rpc_client_sync_generic_attrs,
	Rpc_client_sync_inventory_drop_all,
	Rpc_client_sync_inventory_stack_items,
	Rpc_client_sync_inventory_swap_items,
	Rpc_client_sync_map,
	Rpc_client_sync_objs_position_facing,
	Rpc_client_sync_objs_position_rotation,
	Rpc_client_sync_pick_to_inventory,
	Rpc_client_sync_pickup_armor,
	Rpc_client_sync_pickup_potion,
	Rpc_client_sync_pickup_weapon,
	Rpc_client_sync_pickup_weapon_unit,
	Rpc_client_sync_player_join_info,
	Rpc_client_sync_predict_objs_position,
	Rpc_client_sync_sword_complete,
	Rpc_client_sync_trigger_enter,
	Rpc_client_sync_trigger_exit,
	Rpc_client_team_chat,
	Rpc_client_use_skill,
	Rpc_client_weapon_fire: return "client"
case
	Rpc_friend_add,
	Rpc_friend_del,
	Rpc_friend_list: return "friend"
case
	Rpc_game_agree_invite,
	Rpc_game_battle_begin,
	Rpc_game_become_captain,
	Rpc_game_daily_sign_in,
	Rpc_game_del_mail,
	Rpc_game_exit_team,
	Rpc_game_friend_add,
	Rpc_game_friend_del,
	Rpc_game_friend_list,
	Rpc_game_get_mail,
	Rpc_game_get_show_info,
	Rpc_game_get_team_show_info,
	Rpc_game_heart_beat,
	Rpc_game_join_team,
	Rpc_game_look_over_daily_sign_in,
	Rpc_game_move_player_db,
	Rpc_game_move_player_db2,
	Rpc_game_on_battle_end,
	Rpc_game_permit_player,
	Rpc_game_player_info,
	Rpc_game_player_set_name,
	Rpc_game_read_mail,
	Rpc_game_season_info,
	Rpc_game_take_all_mail_item,
	Rpc_game_team_chat,
	Rpc_game_ui_guns,
	Rpc_game_ui_heros,
	Rpc_game_whitelist_add,
	Rpc_game_whitelist_del,
	Rpc_game_write_db_battle_info: return "game"
case
	Rpc_login_account_login,
	Rpc_login_bulletin,
	Rpc_login_del_account_cache,
	Rpc_login_get_game_list,
	Rpc_login_gift_get,
	Rpc_login_move_player_db,
	Rpc_login_send_email,
	Rpc_login_to_center_by_str: return conf.GameName
case
	Rpc_cross_relay_battle_data,
	Rpc_cross_relay_to_game: return "cross"
case
	Rpc_file_delete,
	Rpc_file_update_list: return "file"}
return ""}