//Generated by common/gen_conf

package conf

import "sync"

var (
	_csv		 *csv
	_csvMutex sync.Mutex
)

func Csv() *csv {
	_csvMutex.Lock()
	ret := _csv //拷贝到栈上
	_csvMutex.Unlock()
	return ret
}
func (v *csv) Init() {
	_csvMutex.Lock()
	_csv = v
	_csvMutex.Unlock()
}
