// Generated by GoServer/src/generate
// Don't edit !
package rpc
import (
	"nets"
	"generate_out/rpc/enum"
	"svr_game/gm"
	"svr_game/player"
	
)
func init() {
	
		nets.RegRpc(map[uint16]nets.RpcFunc{
			enum.Rpc_game_player_agrs_set: player.Rpc_game_player_agrs_set,
			enum.Rpc_game_player_agrs_get: player.Rpc_game_player_agrs_get,
			enum.Rpc_game_permit_player: player.Rpc_game_permit_player,
			enum.Rpc_game_whitelist_add: player.Rpc_game_whitelist_add,
			enum.Rpc_game_whitelist_del: player.Rpc_game_whitelist_del,
			enum.Rpc_set_identity: player.Rpc_set_identity,
			enum.Rpc_game_move_player_db2: player.Rpc_game_move_player_db2,
			enum.Rpc_recv_player_msg: player.Rpc_recv_player_msg,
			
		})
	
	
		player.RegPlayerRpc(map[uint16]player.PlayerRpc{
			enum.Rpc_game_write_db_battle_info: player.Rpc_game_write_db_battle_info,
			enum.Rpc_game_on_battle_end: player.Rpc_game_on_battle_end,
			enum.Rpc_game_ui_heros: player.Rpc_game_ui_heros,
			enum.Rpc_game_ui_guns: player.Rpc_game_ui_guns,
			enum.Rpc_game_daily_sign_in: player.Rpc_game_daily_sign_in,
			enum.Rpc_game_look_over_daily_sign_in: player.Rpc_game_look_over_daily_sign_in,
			enum.Rpc_game_friend_add: player.Rpc_game_friend_add,
			enum.Rpc_game_friend_del: player.Rpc_game_friend_del,
			enum.Rpc_game_friend_list: player.Rpc_game_friend_list,
			enum.Rpc_game_heart_beat: player.Rpc_game_heart_beat,
			enum.Rpc_game_player_info: player.Rpc_game_player_info,
			enum.Rpc_game_player_set_name: player.Rpc_game_player_set_name,
			enum.Rpc_game_get_mail: player.Rpc_game_get_mail,
			enum.Rpc_game_read_mail: player.Rpc_game_read_mail,
			enum.Rpc_game_del_mail: player.Rpc_game_del_mail,
			enum.Rpc_game_take_all_mail_item: player.Rpc_game_take_all_mail_item,
			enum.Rpc_game_move_player_db: player.Rpc_game_move_player_db,
			enum.Rpc_game_season_info: player.Rpc_game_season_info,
			enum.Rpc_game_get_show_info: player.Rpc_game_get_show_info,
			enum.Rpc_game_battle_begin: player.Rpc_game_battle_begin,
			enum.Rpc_game_exit_team: player.Rpc_game_exit_team,
			enum.Rpc_game_join_team: player.Rpc_game_join_team,
			enum.Rpc_game_agree_invite: player.Rpc_game_agree_invite,
			enum.Rpc_game_become_captain: player.Rpc_game_become_captain,
			enum.Rpc_game_get_team_show_info: player.Rpc_game_get_team_show_info,
			enum.Rpc_game_team_chat: player.Rpc_game_team_chat,
			
		})
	
	
		nets.RegHttpHandler(map[string]nets.HttpHandle{
			"/show_player": gm.Http_show_player,
			
		})
	
}
