//Generated by common/gen_conf

package conf

import "sync"

var (
	_pingxxSub pingxxSub
	_mutex	sync.Mutex
)

func PingxxSub() pingxxSub {
	_mutex.Lock()
	ret := _pingxxSub //拷贝到栈上
	_mutex.Unlock()
	return ret
}
func (v pingxxSub) Init() {
	_mutex.Lock()
	_pingxxSub = v
	_mutex.Unlock()
}
