
// Generated by GoServer/src/generat
// Don't edit !
package rpc
import (
	"common/net/register"
	"generate_out/rpc/enum"
	
	
	"svr_game/logic/cloud"
	
	"svr_game/logic/player"
)
func init() {
	register.RegTcpRpc(map[uint16]register.TcpRpc{
		
		enum.Rpc_game_battle_ack: player.Rpc_game_battle_ack,
	})
	register.RegHttpRpc(map[uint16]register.HttpRpc{
		
		enum.Rpc_game_get_cloud_archive_change_times: cloud.Rpc_game_get_cloud_archive_change_times,
		enum.Rpc_game_upload_save_data: cloud.Rpc_game_upload_save_data,
		enum.Rpc_game_download_save_data: cloud.Rpc_game_download_save_data,
		enum.Rpc_game_login: player.Rpc_game_login,
		enum.Rpc_game_player_create: player.Rpc_game_player_create,
		enum.Rpc_game_login_token: player.Rpc_game_login_token,
		enum.Rpc_game_bind_cloud_archive: player.Rpc_game_bind_cloud_archive,
		enum.Rpc_game_get_cloud_archive: player.Rpc_game_get_cloud_archive,
	})
	register.RegHttpPlayerRpc(map[uint16]register.HttpPlayerRpc{
		
		enum.Rpc_game_battle_begin: player.Rpc_game_battle_begin,
		enum.Rpc_game_probe_login_battle: player.Rpc_game_probe_login_battle,
		enum.Rpc_game_friend_list: player.Rpc_game_friend_list,
		enum.Rpc_game_friend_apply: player.Rpc_game_friend_apply,
		enum.Rpc_game_friend_agree: player.Rpc_game_friend_agree,
		enum.Rpc_game_friend_refuse: player.Rpc_game_friend_refuse,
		enum.Rpc_game_friend_del: player.Rpc_game_friend_del,
		enum.Rpc_game_logout: player.Rpc_game_logout,
		enum.Rpc_game_heart_beat: player.Rpc_game_heart_beat,
		enum.Rpc_game_get_mail: player.Rpc_game_get_mail,
		enum.Rpc_game_read_mail: player.Rpc_game_read_mail,
		enum.Rpc_game_del_mail: player.Rpc_game_del_mail,
		enum.Rpc_game_take_mail_item: player.Rpc_game_take_mail_item,
		enum.Rpc_game_take_all_mail_item: player.Rpc_game_take_all_mail_item,
		enum.Rpc_game_create_team: player.Rpc_game_create_team,
		enum.Rpc_game_exit_team: player.Rpc_game_exit_team,
		enum.Rpc_game_get_team_info: player.Rpc_game_get_team_info,
		enum.Rpc_game_invite_friend: player.Rpc_game_invite_friend,
		enum.Rpc_game_agree_join_team: player.Rpc_game_agree_join_team,
		enum.Rpc_game_send_team_chat: player.Rpc_game_send_team_chat,
	})
	register.RegHttpHandler(map[string]register.HttpHandle{
		
	})
}
