// Generated by GoServer/src/generate
// Don't edit !
package rpc
import (
	"nets"
	
	"shared_svr/svr_dns/logic"
	
)
func init() {
	
	
	
	
		nets.RegHttpHandler(map[string]nets.HttpHandle{
			"/svr_list": logic.Http_svr_list,
			
		})
	
}
