
// Generated by GoServer/src/generat
// Don't edit !
package rpc
import (
	"common/net/register"
	"generate_out/rpc/enum"
	
	
	"svr_sdk/logic/huluxia"
	
	"svr_sdk/logic/iqiyi"
	
	"svr_sdk/logic"
)
func init() {
	register.RegTcpRpc(map[uint16]register.TcpRpc{
		
	})
	register.RegHttpRpc(map[uint16]register.HttpRpc{
		
		enum.Rpc_sdk_echo: logic.Rpc_sdk_echo,
	})
	register.RegHttpPlayerRpc(map[uint16]register.HttpPlayerRpc{
		
	})
	register.RegHttpHandler(map[string]register.HttpHandle{
		
		"pre_buy_request": logic.Http_pre_buy_request,
		"query_order": logic.Http_query_order,
		"confirm_order": logic.Http_confirm_order,
		"huluxia_order_success": huluxia.Http_huluxia_order_success,
		"iqiyi_order_success": iqiyi.Http_iqiyi_order_success,
	})
}
