//Generated by common/gen_conf

package conf

import "sync"

var (
	_svrCsv		 *svrCsv
	_svrCsvMutex sync.Mutex
)

func SvrCsv() *svrCsv {
	_svrCsvMutex.Lock()
	ret := _svrCsv //拷贝到栈上
	_svrCsvMutex.Unlock()
	return ret
}
func (v *svrCsv) Init() {
	_svrCsvMutex.Lock()
	_svrCsv = v
	_svrCsvMutex.Unlock()
}
